version: "3.7"

#x-common:
#  - &DB_ROOTPASS: passw0rd
#  - &DB_PASS: db
#  - &DB_USER: db
#  - &DB_NAME: db

services:
  metabase:
    image: metabase/metabase
    ports:
      - 10081:3000

  mongoexpress:
    image: mongo-express
    depends_on:
      - logdb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: logdb
    ports:
      - 8081:8081

  logdb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: fluentd
    volumes:
      - mongo:/data/db
      - ./log/init:/docker-entrypoint-initdb.d

  log:
    #image: fluent/fluentd
    build:
      context: ./
      dockerfile: ./log/Dockerfile
    ports:
      - 24224:24224
      - 24225:24225
      - 24224:24224/udp
    volumes:
      - ./log/etc:/fluentd/etc
    environment:
      FLUENTD_CONF: fluentd.conf

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/home/node/frontapp/src
      - ./frontend/customize:/home/node/frontapp/customize
    tty: true
    command: bash
    ports:
      - 10080:4200

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/customize:/home/node/app/customize
    tty: true
    command: bash
    #  args:
    #    http_proxy: ${http_proxy}
    #    https_proxy: ${http_proxy}
    #environment:
    #volumes:
    #ports:
    #entrypoint:
    #command:

volumes:
  mongo:
    driver: "local"

